# Generated by Django 2.2.3 on 2019-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('start_indoors_begin', models.CharField(max_length=150)),
                ('start_indoors_end', models.CharField(max_length=150)),
                ('start_outdoors_begin', models.CharField(max_length=150)),
                ('start_outdoors_end', models.CharField(max_length=150)),
                ('transplant_begin', models.CharField(max_length=150)),
                ('transplant_end', models.CharField(max_length=150)),
                ('start_indoors_fall_begin', models.CharField(max_length=150)),
                ('start_indoors_fall_end', models.CharField(max_length=150)),
                ('transplant_fall_begin', models.CharField(max_length=150)),
                ('transplant_fall_end', models.CharField(max_length=150)),
                ('start_outdoors_fall_begin', models.CharField(max_length=150)),
                ('start_outdoors_fall_end', models.CharField(max_length=150)),
            ],
        ),
    ]
